### ISSUE TITLE
Update glob-parent to 5.1.2 to fix ReDoS

### ISSUE THREAD

**Issue by leonardoviveiros** [agutoli/serverless-layers#102]
# Update `glob-parent` to 5.1.2

The latest stable version of `serverless-layers` that is `2.5.3` is using `glob-parent@2.0.0` which is vulnerable to regular expression denial of service.

Please release a new version that is stable (not [2.5.4-beta.1](https://www.npmjs.com/package/serverless-layers/v/2.5.4-beta.1)) that contains this fix.

It's a High vulnerability that's impacting users of your library.

**Comment by agutoli** [comment]
done
