### ISSUE TITLE
You're currently using incompatible version [v16.14.2]

### ISSUE THREAD

**Issue by Shereef** [agutoli/serverless-layers#107]
but every thing works great
is it time to add it to compatible versions ?

**Comment by agutoli** [comment]
I reckon it's important to at least `WARN` that you are using a different version than runtime. It could cause issues like features that is supported for one version but not for other.
 
<img width="681" alt="Screen Shot 2022-12-23 at 7 36 25 pm" src="https://user-images.githubusercontent.com/298845/209302094-ddff4d16-936b-4a69-8eb5-b0986a0a6521.png">
