### ISSUE TITLE
devDependecies removed before package builded 

### ISSUE THREAD

**Issue by mokone91** [agutoli/serverless-layers#117]
Hi! 
I use serverless-webpack plugin, when i deploy app it throws  `Cannot find module 'webpack-node-externals'` because plugin skip dev modules

**Comment by agutoli** [comment]
Why would you need `webpack-node-externals` in the bundle inside the lambda? I reckon that's exactly right. If you are trying to do something specific that requires that module, would make sense to move from `devDependencies` to `dependencies`.
