### ISSUE TITLE
Custom environment setup

### ISSUE THREAD

**Issue by mehtatejas** [agutoli/serverless-layers#12]
Hi,
  I am using pupperteer. During deployment I need to run following command :

`
rm -rf node_modules/;
env PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 npm install;
serverless deploy;
`
However when I use serverless-layers, node-modules are re-installing. and I have no control to set environment. Kindly guide.

**Comment by agutoli** [comment]
Hi, @mehtatejas. 

What is your OS?

I just created a new option to make it more "agnostic" and also an improvement over function which installs node dependencies. Possibly, It can fix this issue, if not, try the new option `customInstallationCommand`.


```js
execSync(cmd, {
  cwd: this.nodeJsDir,
  env: process.env
})
```


```yml
custom:
  serverless-layers:
    customInstallationCommand: "yarn"
```

**Comment by mehtatejas** [comment]
Hi,
  I am using bitbucket pipeline. customInstallationCommand works fine.
