### ISSUE TITLE
Deploying existing package

### ISSUE THREAD

**Issue by tim-stasse** [agutoli/serverless-layers#14]
Deploying an existing service package using the command `sls deploy --package .serverless` results in a TypeError: `Cannot read property 'getOutputs' of undefined`. This is because the separate deploy command hasn't initialized the cloudFormation service (or any other service), and `this.cloudFormationService` is undefined.

**Comment by agutoli** [comment]
@thanks to fix it, @tim-stasse!

I just published a new release `serverless-layers@1.3.3`.

**Comment by tim-stasse** [comment]
No problem. Thanks @agutoli  for accepting my contribution.
