### ISSUE TITLE
Bucket doesn't exist

### ISSUE THREAD

**Issue by obie** [agutoli/serverless-layers#2]
Took a bit of work but got this plugin mostly working with my project (see my PR). Filing an issue because the instructions specify that `deploymentBucket` is a required attribute. However, it gets into the deployment step and fails because I'm trying to apply it to a new service that doesn't have a deployment bucket created on S3 yet. Do I have to _create the S3 bucket manually_, or is there some way to keep it automated the way that serverless framework usually works?

Right now trying to deploy fails for lack of bucket.

```
Serverless Error ---------------------------------------

  Could not locate deployment bucket. Error: The specified bucket does not exist
```

**Comment by agutoli** [comment]
Well, Yeah! It is required because I need to upload some files before create stack in the first time when you sync it.

But after that, you can use the same bucket for all projects. Ex. `your-company-serverless-deployments`

**Comment by agutoli** [comment]
It would be like:

`s3://obie-deployments/serverless/your-serverless-project/{stage}` 

And serverless-layers will create a folder into `s3://obie-deployments/serverless/your-serverless-project/{stage}/layers/**`

**Comment by agutoli** [comment]
I was thinking about another approach as well. Ex.

I can allow you to specify a bucket just for `layers` 

```yml
custom:
  serverless-layers:
    deploymentBucket: "your_fixed_layers_bucket"
```

Then you can keep it like your project (without need to add a root `deploymentBucket`)

What do you think?

**Comment by obie** [comment]
yeah I think that’s a better approach to specify a layers bucket since for instance, how I’m trying to use it now is on an existing project and we already have one deployment bucket per service/stack — created and managed automatically by serverless framework.

__



Obie Fernandez
Mexico City, Mexico

+1 404 934 9201
+52 55 1168 9848
obiefernandez.com

**Comment by agutoli** [comment]
Cool. Try lastest version plz `1.0.5`

```yml
custom:
  serverless-layers:
    packagePath: './myfolder/package.json'
    layersDeploymentBucket: "your_layers_bucket"
```

**Comment by agutoli** [comment]
@obie Let me know if it works for you and if I can close this issue plz?

**Comment by agutoli** [comment]
Hey, @obie . Is it working for you? Can I close this issue?

**Comment by obie** [comment]
I’ve been very busy with other work but will try to test it later today, thanks.

__



Obie Fernandez
Mexico City, Mexico

+1 404 934 9201
+52 55 1168 9848
obiefernandez.com
