### ISSUE TITLE
[LayersPlugin]: package.json does not exists at bucket...

### ISSUE THREAD

**Issue by mattnakatani** [agutoli/serverless-layers#20]
I am getting an error when trying to deploy. I am using a newly created bucket.

**Comment by mattnakatani** [comment]
i copied package.json to the bucket and still getting the error.

**Comment by agutoli** [comment]
Hi @mattnakatani can you share the error, please? Are you sure is not a policy/permission error?

**Comment by agutoli** [comment]
Hi @mattnakatani Can I close that issue?

**Comment by mattnakatani** [comment]
hi @agutoli we ended up not using this for our project.
