### ISSUE TITLE
sls remove does not delete created layers

### ISSUE THREAD

**Issue by thopaw** [agutoli/serverless-layers#23]
After I removed the service with `sls remove` the layers created by the serverless-layers plugin are not cleaned up.
Also the resources created in the Layer Bucket are not cleaned up.

**Comment by agutoli** [comment]
You are right, @thopaw. I didn't implement that till today.

Can you check last version pls? `serverless-layers@1.5.0`

**Comment by thopaw** [comment]
@agutoli : Is this feature in this version?
Also, it might be cool if not used layers are pruned also when you build a new layer.
This is probably only possible for layers that are privately used in the project as you can not know if the layer is used elsewhere.
