### ISSUE TITLE
layersDeploymentBucket isn't specified

### ISSUE THREAD

**Issue by nikueater** [agutoli/serverless-layers#24]
Thanks for a good plugin!

Even though I set "layersDeploymentBucket" according the README, I got the message _**"Error: Please, you should specify "deploymentBucket" or "layersDeploymentBucket" option for this plugin!"**_ 

Isn't "custom.serverless-layers.layersDeploymentBucket" overwritten with null when "provider.deploymentBucket" isn't set?

https://github.com/agutoli/serverless-layers/blob/d2f0c36df777d523e99159f3a602ada9d5e899ad/src/index.js#L70

**Comment by agutoli** [comment]
I appreciate, @nikueater !

Can you try last version `2.0.3-alpha`?

**Comment by nikueater** [comment]
Thanks, @agutoli !
I updated it and it worked.
