### ISSUE TITLE
Comparing package.json does not work properly if package.json is in another directory

### ISSUE THREAD

**Issue by CartierDiamonds** [agutoli/serverless-layers#25]
If i specify a different dependenciesPath other than the current directory, it will always compare the package.json in s3 to the package.json in the current directory, resulting in a new layer being created every single deploy. It should compare the package.json in the dependenciesPath specified

**Comment by agutoli** [comment]
Hi @CartierDiamonds, sorry about that. I just push a new release. 

Can you try `2.0.4-alpha`, please?

Let me know if that works for you.

**Comment by CartierDiamonds** [comment]
Hey, my apologies for the late reply, can the new version be published to npm?
