### ISSUE TITLE
Private npm package does not work

### ISSUE THREAD

**Issue by Capelinha** [agutoli/serverless-layers#36]
Hi, I'm using some private packages from npm and after I upgraded from version 1.5.0 to the latest available I'm having problems with 404 error in my private packages. Can you help me?

![image](https://user-images.githubusercontent.com/10324664/81242778-64856280-8fe4-11ea-97e7-229ac2eb469b.png)

**Comment by agutoli** [comment]
Hey @Capelinha I just pushed a new version which `.npmrc` file will be copied by default if exists.

**Comment by Capelinha** [comment]
Thanks, it worked perfectly 🙋🏻‍♂️
