### ISSUE TITLE
Support lockfiles

### ISSUE THREAD

**Issue by dankelleher** [agutoli/serverless-layers#4]
This is a fantastic plugin, and there is just one thing that is making me hesitant about using it in production.

As far as I can see, if a change is made to package-lock.json / yarn.lock (meaning a different version of a dependency is installed) this is not picked up by the plugin and the layer is not recreated.

Are there any plans to support lockfiles? I had a quick look at the code but could not see an obvious way to do it.

**Comment by agutoli** [comment]
I am on it. 

trying to figure out a good way to create this feature.

**Comment by dankelleher** [comment]
Maybe one option would be just to check the timestamp on the package-lock. If it has changed since the one in the bucket, just rebuild. BTW I guess this plugin only supports npm right now? so we don't care about yarn.lock?

**Comment by agutoli** [comment]
Hey, @dankelleher. Try release `serverless-layers@1.2.0-alpha`. I just added support for `yarn` package manager and `lock` files. Let me know if it helps you.

Kindly.

B. Agutoli

**Comment by dankelleher** [comment]
Hi @agutoli . Thanks - I have tested this a little. Unfortunately it brings back the devDependencies issue. I have a fix for it in: https://github.com/agutoli/serverless-layers/pull/10
