### ISSUE TITLE
Should not install dev dependencies

### ISSUE THREAD

**Issue by dankelleher** [agutoli/serverless-layers#5]
At the moment, because of a small bug, the list of dependencies being passed to npm-install-package is [], which leads to it making the call `npm i` (which installs all packages, including dev dependencies). In one of my projects this pushes us over the 250MB maximum limit, whereas without dev dependencies I'm at 130MB.

**Comment by dankelleher** [comment]
Fix here: https://github.com/agutoli/serverless-layers/pull/6

**Comment by agutoli** [comment]
Hi, @dankelleher 
Actually, It is not installing devDependencies, just consider "dependencies".

"Should not install dev dependencies"

**Comment by dankelleher** [comment]
Right. But I think that there is a bug there in that the list sent to the
npm install package is empty, so npm install is called without any
arguments, leading to it installing everything. I checked the generated
layer and it had my devDependencies in it. The PR has more details.
