### ISSUE TITLE
Minimal configuration?

### ISSUE THREAD

**Issue by interspoerri** [agutoli/serverless-layers#58]
My lambda layer is getting created nicely, but all of its contents are still getting included in the main lambda deployment! That is, the lambda itself is still as large as it was before I set up a layer.

Besides including the plugin, I just added the tiniest config to my serverless.yml, in the custom section:
```
  serverless-layers:
    layersDeploymentBucket: foo-lambda-layers
```

What am I doing wrong?

**Comment by agutoli** [comment]
Hi @interspoerri , It looks right, but I need more info to identify your issue. You could paste your serverless.yml file removing sensible data/names etc, so  I could try to reproduce that error. 

https://github.com/agutoli/serverless-layers/blob/alpha/demos/simple/serverless.yml

**Comment by interspoerri** [comment]
Thank you!

Attaching my full serverless.yml...
[serverless.yml.txt](https://github.com/agutoli/serverless-layers/files/5538903/serverless.yml.txt)

**Comment by interspoerri** [comment]
Any idea?

Adding an explicit provider deploymentBucket didn't seem to help...

**Comment by agutoli** [comment]
Hi @interspoerri about " but all of its contents are still getting included in the main lambda deployment". Are you able to see node_modules in the lambda deployment as well? 

Also, I guess  `serverless-python-requirements` plugin is potentially creating package with these all dependencies (not sure). 

Finally, I saw your serverless.yml and it shows just excluding `node_modules` folder, are you able to see node_modules into that zip file? If not, `package.exclude` is working fine. 

```yml
package:
  exclude:
    - '**'
```

**Comment by interspoerri** [comment]
Yes! Thank you! For the python-requirements, it makes sense to configure the serverless-python-requirements plugin to use a lambda layer.
