### ISSUE TITLE
str.indexOf is not a function

### ISSUE THREAD

**Issue by orr-levinger** [agutoli/serverless-layers#65]
Serverless: [ LayersPlugin ]: => default
... ○ Downloading package.json from bucket...
... ○ package.json does not exists at bucket...
... ⊗ =============================================================
... ⊗ NOTE: You're currently using incompatible version [v14.15.1]
... ⊗ =============================================================

... ○  Changes identified ! Re-installing...
... ∅ [warning] ".npmrc" file does not exists!
... ∅ [warning] "yarn.lock" file does not exists!
npm WARN blind-chat-backend@1.0.0 No description

added 180 packages from 151 contributors and audited 2546 packages in 14.671s

28 packages are looking for funding
  run `npm fund` for details

found 72 vulnerabilities (1 low, 68 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details

... ○ Created layer package /Users/orrlevinger/projects/BlindChat/blind-chat-backend/.serverless/sls-blind-chat-dev-stack-nodejs-default.zip (24.6 MB)
... ○ Uploading layer package...
str.indexOf is not a function

**Comment by cdash04** [comment]
@orr-levinger  can you tell why you closed it? I have the same issues and your feedback could help me 😄

**Comment by light320180** [comment]
I have the same issues and your feedback could help me,too
