### ISSUE TITLE
Private npm package support

### ISSUE THREAD

**Issue by scvgoe** [agutoli/serverless-layers#7]
Hi

I'm using some private npm packages in my project.

Even though, we are using this command `echo "//registry.npmjs.org/:_authToken=$(NPM-TOKEN)" > ~/.npmrc`, it cannot find our private npm packages.

**Comment by scvgoe** [comment]
I think that a package `npm-install-package` doesn't support private npm packgae.

**Comment by agutoli** [comment]
Hi, @scvgoe. Please try `serverless-layers@1.2.0-alpha` release and let me know if it works for you.
