### ISSUE TITLE
always use latest layer version

### ISSUE THREAD

**Issue by orr-levinger** [agutoli/serverless-layers#79]
When i redeploy my lambda it uses the layer version 1 even though i the latest version is 2 after changing the package.json
i changed it manually and it works but the plugin should do it for me

**Comment by RaissaBergamini** [comment]
Had the same issue in a project when deploying. It was on layer version 4, a version 5 was created but the lambdas were not updated to it on its own. @orr-levinger did you figure out what was the issue?

**Comment by brunocasado** [comment]
same here

**Comment by agutoli** [comment]
Bugfix version: `[2.6.1](https://www.npmjs.com/package/serverless-layers/v/2.6.1)`. Please let me know if it works.
