### ISSUE TITLE
Problem with windows style file paths when uploading to s3

### ISSUE THREAD

**Issue by erensahin** [agutoli/serverless-layers#8]
Hello,

Firstly, thank you for this amazing plug-in!

I have trouble using the package on windows due to windows file paths are constructed by \ characters. 

When uploading the layers zip file and package.json file, the files are uploaded as single files on the main bucket folder, the nesting folders are not constucted.

The files are formed as 

> serverless\\{service_name}\\{stage}\layers\package.json

 and 

> serverless\\{service_name}\\{stage}\layers\\{service_name}-{stage}.zip

I guess they are supposed to be uploaded as a folder structure.

Thanks in advance.

**Comment by agutoli** [comment]
@erensahin Hey, thanks! 

So, what version are you using?

**Comment by erensahin** [comment]
Hey @agutoli !

I tried both v1.1.1 and v1.2.5-alpha and faced with the same issue.

**Comment by agutoli** [comment]
hey @erensahin, please try `serverless-layers@1.3.2` version. It should work now.

**Comment by erensahin** [comment]
hey @agutoli, it worked. Thanks!

**Comment by austindimmer** [comment]
I observe this (or a similar) issue in "serverless-layers": "^2.2.4", and thanks!
