### ISSUE TITLE
serverless.yml provider and region issue

### ISSUE THREAD

**Issue by slaphead** [agutoli/serverless-layers#9]
If the provider region is using an argument/variable and it is not defined, the default is not used and serverless commands hang.

This is how to reproduce it:
- In serverless.yml set the region under provider with an optional:
```
provider:
    region: ${opt:stage, "us-east-1"}
```
- run serverless print to see it hang. Any sls command will hang:
`sls print`

- To unblock it, just make sure the provider region has a value:
`sls print --region=us-east-1`

We will need to still try and see where this is being caused in the code, but thought this might help anyone else seeing this issue in the meantime.

**Comment by agutoli** [comment]
Hi, @slaphead.

Try the new release `1.2.6`. 

Thanks to reporting this bug. 

Bugfix: https://github.com/agutoli/serverless-layers/pull/11
