### ISSUE TITLE
Unable to attach layers to the existing lambda

### ISSUE THREAD

**Issue by VaddeRam** [agutoli/serverless-layers#97]
I'm trying to attach common layers to the 5 lambda functions

![image](https://user-images.githubusercontent.com/100859530/156936347-5062507c-b9bd-4838-abec-0691dc45af89.png)

Have defined one sample function in the code,

service: user-rep
description: user-rep-tool
frameworkVersion: ^3.0.0
useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-layers

package:
  individually: true  

serverless-layers:
      layersDeploymentBucket: ${self:service}-tool-${self:provider.stage}-layers
      functions: # optional
        - query-access-requests
        - dispose-access-request
        - create-access-request
        - query-affiliates
        - lambda-authorizer
        - pre-token-trigger
      dependenciesPath: ./package.json

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs14.x

functions:
 query-affiliates:
    handler: src/lambda/query-affiliates/index.handler
    architecture: arm64

**Comment by MHekert** [comment]
I had the same issue when upgrading from 2.5.2 to 2.5.4. Additionally, it removed layers that were already added to lambdas. Downgrade to 2.5.2 fixed it for me.

**Comment by ivanmartos** [comment]
I had similar issue with `2.5.4`. Downgrade to `2.5.3` solved it

**Comment by agutoli** [comment]
Bugfix (not release yet)
https://github.com/agutoli/serverless-layers/pull/128
